name: Batch Airflow Run 

on:
    schedule: 
        - cron: '0 0 * * *' #every day at midnight UTC
    workflow_dispatch: # manual trigger test 
jobs: 
    run_pipeline:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout repository 
              uses: actions/checkout@v3 
            
            - name: Set up Fly.io CLI 
              uses: superfly/flyctl-actions/setup-flyctl@master 
              with: 
                version: '0.2.10'

            - name: Fly.io Airflow Start 
              run: | 
                echo "Starting Airflow..."
                flyctl machine start 8ee01dc7d723e8 -a london-restaurant-hygiene-pipeline
              env: 
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
   
            - name: Waiting for Airflow to be fully up and running the Dag
              run: |
                echo "waiting for 5 minutes to ensure Airflow is fully up and run the DAG"
                sleep 300 

            - name: Fly.io Airflow Stop 
              if: always() # Ensure this step runs even if previous steps fail
              run: | 
                echo "Stopping Airflow...to prevent billing"
                flyctl machine stop 8ee01dc7d723e8 -a london-restaurant-hygiene-pipeline
              env: 
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}