name: Batch Airflow Run 

on:
    schedule: 
        - cron: '0 0 * * *' #every day at midnight UTC
    workflow_dispatch: # manual trigger test 
jobs: 
    run_pipeline:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout repository 
              uses: actions/checkout@v3 
            
            - name: Set up Fly.io CLI 
              uses: superfly/flyctl-actions/setup-flyctl@master 
              with: 
                version: '0.2.10'

            - name: Fly.io Airflow Start 
              run: | 
                echo "Starting Airflow..."
                flyctl machine start 8ee01dc7d723e8 -a london-restaurant-hygiene-pipeline
              env: 
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
   
            - name: Airflow Booting wait nd DAG status check 
              run: |
                echo "Check Airflow booting status and DAG completion..."

                
                MAX_ATTEMPTS=10
                ATTEMPT=1

                while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
                  echo "Checking pipeline status... (Attempt $ATTEMPT/$MAX_ATTEMPTS)"

                  # Fly.io ssh console to check the status of the Airflow DAG run
                  # Status: running, success, failed

                  STATUS=$(flyctl ssh console --command "airflow dags list-runs -d london_restaurant_hygiene_pipeline -o plain --no-backfill | tail -n 1 | awk '{print \$3}'" -a london-restaurant-hygiene-pipeline 2>/dev/null | tr -d '\r\n ' || echo "booting")

                  echo "Current DAG State: [$STATUS]"

                  if [ "$STATUS" = "success" ]; then
                    echo "Success!"
                    exit 0
                  elif [ "$STATUS" = "failed" ]; then
                    echo "[Error] Airflow DAG failed. Please check the logs for more details."
                    exit 1
                  fi

                  sleep 15
                  ATTEMPT=$((ATTEMPT+1))
                done

                echo "[Warning] Timeout! Batch run did not complete within the expected time frame."
                exit 1
              env: 
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


            - name: Fly.io Airflow Stop 
              if: always() # Ensure this step runs even if previous steps fail
              run: | 
                echo "Stopping Airflow...to prevent billing"
                flyctl machine stop 8ee01dc7d723e8 -a london-restaurant-hygiene-pipeline
              env: 
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}